name: Build Podcast
destination: ./_publish
permalink: /:title
markdown: redcarpet
url: http://localhost:4000

exclude: ['sass', 'node_modules', 'Gruntfile.js', 'package.json', 'readme.md', 'js', 'scripts', 'build-podcast.yml', 'templates',
  '001-webdevtools',
  '002-terminal',
  '003-html5boilerplate',
  '004-git',
  '005-markdown',
  '006-wordpress',
  '007-web-fonts',
  '008-sublime-text',
  '009-package-managers',
  '010-sass',
  '011-responsive',
  '012-zen-coding',
  '013-requirejs',
  '014-local-web-servers',
  '015-github',
  '016-yslow',
  '017-jade',
  '018-fireworks',
  '019-bash',
  '020-nanoc',
  '021-gruntjs',
  '022-ssh',
  '023-rails',
  '024-heroku',
  '025-virtualbox',
  '026-modernizr',
  '027-yeoman',
  '028-api',
  '029-oh-my-zsh',
  '030-closure',
  '031-inuitcss',
  '032-travisci',
  '033-aws',
  '034-lodash',
  '035-capistrano',
  '036-apache',
  '037-jekyll',
  '038-alfred',
  '039-vagrant',
  '040-sinatra',
  '041-vim',
  '042-backbonejs',
  '043-sql',
  '044-node',
  '045-bower',
  '046-regex',
  '047-styleguide',
  '048-phantomjs',
  '049-cloudflare',
  '050-dom',
  '051-svg',
  '052-tmux',
  '053-command-line-apps',
  '054-d3js',
  '055-ubuntu',
  '056-angularjs',
  '057-ghost',
  '058-rspec',
  '059-git-flow',
  '060-gulp'
]
